all: 4 6 8 4s 6s 8s

4:
	qrencode -o gaia4.png 'http://gaianysus.com/gaia-4/'
6:
	qrencode -o gaia6.png 'http://gaianysus.com/gaia-6/'
8:
	qrencode -o gaia8.png 'http://gaianysus.com/gaia-8/'

4s:
	qrencode -o gaia4.png 'http://gaianysus.com/gaia-4S/'
6s:
	qrencode -o gaia6.png 'http://gaianysus.com/gaia-6S/'
8s:
	qrencode -o gaia8.png 'http://gaianysus.com/gaia-8S/'
